export const SET_FAVORITE = 'SET_FAVORITE';
export const SET_RELATED_RESTAURANTS = 'SET_RELATED_RESTAURANTS';
export const CLEAR_RELATED_RESTAURANTS = 'CLEAR_RELATED_RESTAURANTS';
export const ADD_BREADCRUMBS = 'ADD_BREADCRUMBS';
export const DELETE_LAST_BREADCRUMBS = 'DELETE_LAST_BREADCRUMBS';
