export const INPUT_PROPS_MOCK = {
  type: 'text',
  hasSearchIcon: true,
  className: 'default-className',
  placeholder: 'Default placeholder',
  value: '',
  disabled: false,
  readOnly: false,
  name: 'default-input-name',
  id: 'default-input-id',
  step: 1,
  autoComplete: 'no',
  maxLength: 70,
  minLength: 1,
  onFocus: () => {},
  onBlur: () => {},
};
