export const RESTAURANTS = [
  {
    id: 234,
    imgSrc: '/images/thumb-1.webp',
    imgAlt: 'restaurant',
    title: 'Elephant & Castle',
    link: '',
    firstText: 'Temple Bar',
    secondText: 'Mediterranean',
  },
  {
    id: 5474,
    imgSrc: '/images/thumb-2.webp',
    imgAlt: 'restaurant',
    title: 'Abrecadabra',
    link: '',
    firstText: 'Rathmines',
    secondText: 'Fast food',
  },
  {
    id: 8963,
    imgSrc: '/images/thumb-3.webp',
    imgAlt: 'restaurant',
    title: 'Brothers in law of Harold Cross street',
    link: '',
    firstText: 'Blackrock',
    secondText: 'Mexican',
  },
  {
    id: 4421,
    imgSrc: '/images/thumb-4.webp',
    imgAlt: 'restaurant',
    title: 'Misushi',
    link: '',
    firstText: 'Whitehall',
    secondText: 'Asian',
  },
  {
    id: 2144,
    imgSrc: '/images/thumb-5.webp',
    imgAlt: 'restaurant',
    title: 'Pattaya',
    link: '',
    firstText: 'Clondankin',
    secondText: 'Asian',
  },
];
